### PR TITLE
skip wayland if wayland-protocols version is not sufficient

### LINKED ISSUE #714: Generating xdg-shell-client-protocol.h  error
hi, i Build it on ubuntu16.  but i meet an error as follows:

image

image

i dont know how to solve it . could u help me
thank you

### PR DESCRIPTION
**Pull request by christian-rauch**
On older Ubuntu versions (16.04) `wayland-protocols` is missing `wayland-protocols`. This will attempt the Wayland build but fail. Check for the version and skip wayland insufficient. Fixes #714.

### CODE REVIEW

**Comment by christian-rauch** [comment]
@stevenlovegrove Can you check this?

**Comment by jfenton888** [comment]
I cannot be sure that this is the cause, but I just tried implementing this fix after running into the exact same issue as #714. I am also running Ubuntu 16.04 and cannot update beyond it. 
However now I get errors relating to X11 events not being properly defined. The includes for these are within the same `else()` as Wayland in `components/pango_windowing/CMakeLists.txt`, so I believe it might be the thing causing it.

````
mllax8@ubuntu:~/Documents/EECE4790_Capstone/Pangolin/build$ cmake --build .
CMake Warning at CMakeLists.txt:75 (message):
  Building Tests requested, but Catch2 library not found.


-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- liblz4 Found and Enabled
-- pybind11 v2.7.1 
CMake Warning (dev) at /usr/local/share/cmake-3.22/Modules/CMakeDependentOption.cmake:84 (message):
  Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
  Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  components/pango_python/pybind11/CMakeLists.txt:98 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Python module `setuptools` required for correct wheel filename generation. Please install if needed.
-- Selected Python: '/usr/bin/python2.7'. cmake --build . -t pypangolin_pip_install to use pypangolin module.
-- V4L Found and Enabled
-- ffmpeg Found and Enabled
-- OpenNI Found and Enabled
CMake Warning (dev) at /usr/local/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (WAYLAND_CLIENT) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindWayland.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  components/pango_windowing/CMakeLists.txt:35 (find_package)
  CMakeLists.txt:93 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (WAYLAND_SERVER) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindWayland.cmake:53 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  components/pango_windowing/CMakeLists.txt:35 (find_package)
  CMakeLists.txt:93 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (WAYLAND_EGL) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindWayland.cmake:54 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  components/pango_windowing/CMakeLists.txt:35 (find_package)
  CMakeLists.txt:93 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args`
  (WAYLAND_CURSOR) does not match the name of the calling package (Wayland).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindWayland.cmake:55 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  components/pango_windowing/CMakeLists.txt:35 (find_package)
  CMakeLists.txt:93 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (WAYLAND)
  does not match the name of the calling package (Wayland).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindWayland.cmake:56 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  components/pango_windowing/CMakeLists.txt:35 (find_package)
  CMakeLists.txt:93 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/mllax8/Documents/EECE4790_Capstone/Pangolin/build
[  0%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/file_extension.cpp.o
[  1%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/file_utils.cpp.o
[  1%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/sigstate.cpp.o
[  2%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/threadedfilebuf.cpp.o
[  2%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/avx_math.cpp.o
[  3%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/uri.cpp.o
[  3%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/param_set.cpp.o
[  4%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/factory/factory_registry.cpp.o
[  4%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/factory/factory_help.cpp.o
[  5%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/condition_variable.cpp.o
[  5%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/semaphore.cpp.o
[  6%] Building CXX object CMakeFiles/pango_core.dir/components/pango_core/src/posix/shared_memory_buffer.cpp.o
[  6%] Linking CXX shared library libpango_core.so
[  6%] Built target pango_core
[  6%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/pixel_format.cpp.o
[  7%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io.cpp.o
[  7%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_exr.cpp.o
[  8%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_jpg.cpp.o
[  8%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_lz4.cpp.o
[  9%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_packed12bit.cpp.o
[  9%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_pango.cpp.o
[ 10%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_png.cpp.o
[ 10%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_ppm.cpp.o
[ 11%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_raw.cpp.o
[ 11%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_tga.cpp.o
[ 12%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_bmp.cpp.o
[ 12%] Building CXX object CMakeFiles/pango_image.dir/components/pango_image/src/image_io_zstd.cpp.o
[ 13%] Linking CXX shared library libpango_image.so
[ 13%] Built target pango_image
[ 13%] Embedding /home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_opengl/src/fonts/AnonymousPro.ttf into fonts.cpp
[ 14%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glchar.cpp.o
[ 14%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gldraw.cpp.o
[ 15%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glfont.cpp.o
[ 15%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gltext.cpp.o
[ 16%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/glpangoglu.cpp.o
[ 16%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/gltexturecache.cpp.o
[ 17%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/viewport.cpp.o
[ 17%] Building CXX object CMakeFiles/pango_opengl.dir/components/pango_opengl/src/opengl_render_state.cpp.o
[ 18%] Building CXX object CMakeFiles/pango_opengl.dir/fonts.cpp.o
[ 18%] Linking CXX shared library libpango_opengl.so
[ 18%] Built target pango_opengl
[ 18%] Creating /home/mllax8/Documents/EECE4790_Capstone/Pangolin/build/include/pangolin/factory/RegisterFactoriesWindowInterface.h factory registry header
[ 19%] Building CXX object CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/src/display_x11.cpp: In member function ‘virtual void pangolin::X11Window::ProcessEvents()’:
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/src/display_x11.cpp:403:12: error: no matching function for call to ‘pangolin::MouseEvent::MouseEvent(<brace-enclosed initializer list>)’
            });
            ^
In file included from /home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/X11Window.h:31:0,
                 from /home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/src/display_x11.cpp:35:
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note: candidate: pangolin::MouseEvent::MouseEvent()
 struct PANGOLIN_EXPORT MouseEvent : public WindowInputEvent
                        ^
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note:   candidate expects 0 arguments, 5 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note: candidate: constexpr pangolin::MouseEvent::MouseEvent(const pangolin::MouseEvent&)
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note:   candidate expects 1 argument, 5 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note: candidate: constexpr pangolin::MouseEvent::MouseEvent(pangolin::MouseEvent&&)
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:69:24: note:   candidate expects 1 argument, 5 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/src/display_x11.cpp:413:17: error: no matching function for call to ‘pangolin::MouseMotionEvent::MouseMotionEvent(<brace-enclosed initializer list>)’
                 });
                 ^
In file included from /home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/X11Window.h:31:0,
                 from /home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/src/display_x11.cpp:35:
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: pangolin::MouseMotionEvent::MouseMotionEvent()
 struct PANGOLIN_EXPORT MouseMotionEvent : public WindowInputEvent
                        ^
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 0 arguments, 3 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: constexpr pangolin::MouseMotionEvent::MouseMotionEvent(const pangolin::MouseMotionEvent&)
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 1 argument, 3 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: constexpr pangolin::MouseMotionEvent::MouseMotionEvent(pangolin::MouseMotionEvent&&)
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 1 argument, 3 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/src/display_x11.cpp:418:17: error: no matching function for call to ‘pangolin::MouseMotionEvent::MouseMotionEvent(<brace-enclosed initializer list>)’
                 });
                 ^
In file included from /home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/X11Window.h:31:0,
                 from /home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/src/display_x11.cpp:35:
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: pangolin::MouseMotionEvent::MouseMotionEvent()
 struct PANGOLIN_EXPORT MouseMotionEvent : public WindowInputEvent
                        ^
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 0 arguments, 3 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: constexpr pangolin::MouseMotionEvent::MouseMotionEvent(const pangolin::MouseMotionEvent&)
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 1 argument, 3 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note: candidate: constexpr pangolin::MouseMotionEvent::MouseMotionEvent(pangolin::MouseMotionEvent&&)
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:75:24: note:   candidate expects 1 argument, 3 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/src/display_x11.cpp:471:17: error: no matching function for call to ‘pangolin::KeyboardEvent::KeyboardEvent(<brace-enclosed initializer list>)’
                 });
                 ^
In file included from /home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/X11Window.h:31:0,
                 from /home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/src/display_x11.cpp:35:
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note: candidate: pangolin::KeyboardEvent::KeyboardEvent()
 struct PANGOLIN_EXPORT KeyboardEvent : public WindowInputEvent
                        ^
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note:   candidate expects 0 arguments, 5 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note: candidate: constexpr pangolin::KeyboardEvent::KeyboardEvent(const pangolin::KeyboardEvent&)
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note:   candidate expects 1 argument, 5 provided
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note: candidate: constexpr pangolin::KeyboardEvent::KeyboardEvent(pangolin::KeyboardEvent&&)
/home/mllax8/Documents/EECE4790_Capstone/Pangolin/components/pango_windowing/include/pangolin/windowing/window.h:63:24: note:   candidate expects 1 argument, 5 provided
CMakeFiles/pango_windowing.dir/build.make:79: recipe for target 'CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o' failed
make[2]: *** [CMakeFiles/pango_windowing.dir/components/pango_windowing/src/display_x11.cpp.o] Error 1
CMakeFiles/Makefile2:844: recipe for target 'CMakeFiles/pango_windowing.dir/all' failed
make[1]: *** [CMakeFiles/pango_windowing.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
````

**Comment by christian-rauch** [comment]
I tried reproducing this with 16.04 via the GitHub actions, but it seems that they removed that support after Ubuntu 16.04 went EOL. I am not really motivated to look into this issue for an unsupported Ubuntu version, so I will rely on someone else to send a PR that fixes the build (if this actually is caused by this PR).

**Comment by christian-rauch** [comment]
@jfenton888 I set up a 16.04 VM to test this. The first obstacle is that Panglin needs a newer cmake than what is available in Ubuntu 16.04. After updating cmake to 3.22.2, I am getting errors related to `Eigen3::Eigen`:
```
CMake Error at CMakeLists.txt:88 (add_library):
  Target "pango_display" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
I am getting the same warnings for the package name.

**Comment by jfenton888** [comment]
@christian-rauch I did initially get these issues too. I solved the CMake issue with
````
wget https://cmake.org/files/v3.22/cmake-3.22.2-Linux-x86_64.tar.gz
tar xzf cmake-3.22.2-Linux-x86_64.tar.gz
rm -rf cmake-3.22.2-Linux-x86_64.tar.gz
cd cmake-3.22.3-Linux-x86_64
./configure
make
sudo make install
echo 'export PATH=$HOME/cmake-install/bin:$PATH' >> ~/.bashrc
echo 'export CMAKE_PREFIX_PATH=$HOME/cmake-install:$CMAKE_PREFIX_PATH' >> ~/.bashrc
````
And then the eigen issue 
````
cd ~
wget https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz
tar -xzvf eigen-3.3.9.tar.gz 
cd eigen-3.3.9

mkdir build && cd build
cmake ..
sudo make install
````

And then when building Pangolin I have to explicitly declare the location of this new Eigen
````
git clone --recursive https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin
./scripts/install_prerequisites.sh recommended
git checkout v0.6

mkdir -p build && cd build
cmake .. -DEigen3_DIR=$HOME/eigen-3.3.9/build
cmake --build .
````

**Comment by christian-rauch** [comment]
I am now getting:
```
In file included from /home/christian/Downloads/Pangolin/components/pango_geometry/src/geometry.cpp:28:0:
/home/christian/Downloads/Pangolin/components/pango_geometry/include/pangolin/geometry/geometry.h:34:19: fatal error: variant: No such file or directory
compilation terminated.
```
probably because `variant` is a C++17 feature and the latest GCC in Ubuntu 16.04 (GCC 5.4.0) seems not to support this.

Honestly, there are a lot of hoops you have to jump through to get Pangolin working on Ubuntu 16.04. I am pretty sure there is only a minority that requires to use the latest Pangolin on an outdated Ubuntu and is willing to install cmake, eigen and probably a newer GCC manually to make this work.

**Comment by christian-rauch** [comment]
@stevenlovegrove Can you consider merging this to fix the reported issues (#715, #726 )?

**Comment by christian-rauch** [comment]
I installed a newer GCC from https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test and configured the project like this:
```
$ CC=gcc-9 CXX=g++-9 snap run cmake -B build -GNinja
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
[...]
-- Found WAYLAND_CLIENT: /usr/lib/x86_64-linux-gnu/libwayland-client.so  
-- Found WAYLAND_SERVER: /usr/lib/x86_64-linux-gnu/libwayland-server.so  
-- Found WAYLAND_EGL: /usr/lib/x86_64-linux-gnu/libwayland-egl.so  
-- Found WAYLAND_CURSOR: /usr/lib/x86_64-linux-gnu/libwayland-cursor.so  
-- Found WAYLAND: /usr/lib/x86_64-linux-gnu/libwayland-client.so;/usr/lib/x86_64-linux-gnu/libwayland-server.so;/usr/lib/x86_64-linux-gnu/libwayland-egl.so;/usr/lib/x86_64-linux-gnu/libwayland-cursor.so  
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/christian/Downloads/Pangolin/build
```

I can build and run this on X11. The Wayland backend will be disabled due to the insufficient `wayland-protocol` version.

**Comment by stevenlovegrove** [comment]
My apologies for being AWOL. Thanks so much for spending so much energy on this, Christian. I would also encourage anyone using 16.04 to move on at this point since it has reached end of LTS and will no longer get security updates.
