### ISSUE TITLE
sigslot/signal.hpp in pangolin

### ISSUE THREAD

**Issue by UcefMountacer** [stevenlovegrove/Pangolin#675]
HI,

I get this error when building ORB_SLAM3. I'm using pangolin 0.6 and I keep getting these errors:

This is just a subset, but all of them are about the signal.hpp file.

Thanks for the help
```
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:109:79: error: ‘decay_t’ is not a member of ‘std’; did you mean ‘decay’?
  109 | constexpr bool is_weak_ptr_compatible_v = detail::is_weak_ptr_compatible<std::decay_t<P>>::value;
      |                                                                               ^~~~~~~
      |                                                                               decay
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:109:79: error: ‘decay_t’ is not a member of ‘std’; did you mean ‘decay’?
  109 | constexpr bool is_weak_ptr_compatible_v = detail::is_weak_ptr_compatible<std::decay_t<P>>::value;
      |                                                                               ^~~~~~~
      |                                                                               decay
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:109:87: error: template argument 1 is invalid
  109 | constexpr bool is_weak_ptr_compatible_v = detail::is_weak_ptr_compatible<std::decay_t<P>>::value;
      |                                                                                       ^
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:109:92: error: ‘::value’ has not been declared
  109 | constexpr bool is_weak_ptr_compatible_v = detail::is_weak_ptr_compatible<std::decay_t<P>>::value;
      |                                                                                            ^~~~~
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:132:53: error: ‘remove_pointer_t’ is not a member of ‘std’; did you mean ‘remove_pointer’?
  132 |                                                std::remove_pointer_t<T>>::value;
      |                                                     ^~~~~~~~~~~~~~~~
      |                                                     remove_pointer
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:132:53: error: ‘remove_pointer_t’ is not a member of ‘std’; did you mean ‘remove_pointer’?
  132 |                                                std::remove_pointer_t<T>>::value;
      |                                                     ^~~~~~~~~~~~~~~~
      |                                                     remove_pointer
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:132:70: error: template argument 2 is invalid
  132 |                                                std::remove_pointer_t<T>>::value;
      |                                                                      ^
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:132:75: error: ‘::value’ has not been declared
  132 |                                                std::remove_pointer_t<T>>::value;
      |                                                                           ^~~~~
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:223:32: error: ‘enable_if_t’ is not a member of ‘std’; did you mean ‘enable_if’?
  223 | struct function_traits<T, std::enable_if_t<trait::is_func_v<T>>> {
      |                                ^~~~~~~~~~~
      |                                enable_if
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:223:32: error: ‘enable_if_t’ is not a member of ‘std’; did you mean ‘enable_if’?
  223 | struct function_traits<T, std::enable_if_t<trait::is_func_v<T>>> {
      |                                ^~~~~~~~~~~
      |                                enable_if
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:223:62: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, class> struct sigslot::detail::function_traits’
  223 | struct function_traits<T, std::enable_if_t<trait::is_func_v<T>>> {
      |                                                              ^~
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:223:62: note:   expected a type, got ‘(<expression error> < is_func_v<T>)’
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:223:64: error: expected unqualified-id before ‘>’ token
  223 | struct function_traits<T, std::enable_if_t<trait::is_func_v<T>>> {
      |                                                                ^
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:233:33: error: ‘enable_if_t’ is not a member of ‘std’; did you mean ‘enable_if’?
  233 | struct function_traits<T*, std::enable_if_t<trait::is_func_v<T>>> {
      |                                 ^~~~~~~~~~~
      |                                 enable_if
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:233:33: error: ‘enable_if_t’ is not a member of ‘std’; did you mean ‘enable_if’?
  233 | struct function_traits<T*, std::enable_if_t<trait::is_func_v<T>>> {
      |                                 ^~~~~~~~~~~
      |                                 enable_if
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:233:63: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, class> struct sigslot::detail::function_traits’
  233 | struct function_traits<T*, std::enable_if_t<trait::is_func_v<T>>> {
      |                                                               ^~
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:233:63: note:   expected a type, got ‘(<expression error> < is_func_v<T>)’
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:233:65: error: expected unqualified-id before ‘>’ token
  233 | struct function_traits<T*, std::enable_if_t<trait::is_func_v<T>>> {
      |                                                                 ^
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:243:32: error: ‘enable_if_t’ is not a member of ‘std’; did you mean ‘enable_if’?
  243 | struct function_traits<T, std::enable_if_t<trait::is_pmf_v<T>>> {
      |                                ^~~~~~~~~~~
      |                                enable_if
/home/youssef/Readar/ORB_SLAM3/Pangolin/components/pango_core/include/sigslot/signal.hpp:243:32: error: ‘enable_if_t’ is not a member of ‘std’; did you mean ‘enable_if’?
  243 | struct function_traits<T, std::enable_if_t<trait::is_pmf_v<T>>> {
      |                                ^~~~~~~~~~~
      |                                enable_if

```

**Comment by stevenlovegrove** [comment]
These errors are related to the c++ version being used to compile orbslam. Pangolin requires c++17 on master branch and C++11 I think on the 0.6 tag. Are you sure those errors are from the 0.6 tag?

**Comment by HU-517** [comment]
I have the same problem and want to ask what version of g++ I need to use

**Comment by stevenlovegrove** [comment]
@HU-517 a version which can compile C++11 for the 0.6 tag or C++17 for the master branch. The build server is working with GNU 9.3.0 but I'm sure something from 7+ is likely fine.

**Comment by HU-517** [comment]
I use ubuntu16.04+gcc9.1.0.How should I do?

**Comment by stevenlovegrove** [comment]
If you're getting this error when building OrbSlam, that isn't really something I can help with, beside to recommend that you checkout the v0.6 tag or that you modify the OrbSLAM CMake to use C++17.

**Comment by cbuchxrn** [comment]
Had the same error forcing c++17 worked for me. 
Thanks for the help :D
