### ISSUE TITLE
win10 vs2017 C++17

### ISSUE THREAD

**Issue by oridong** [stevenlovegrove/Pangolin#447]
mpark\variant.hpp(977): error C2131: 表达式的计算结果不是常数
error C2975: “unnamed-parameter”:“mpark::detail::copy_assignment”的模板参数无效，应为编译时常量表达式
mpark\variant.hpp(1599): error C2440: “specialization”: 无法从“int”转换为“mpark::detail::Trait”
note: 强制转换为枚举类型要求显式强制转换(static_cast、C 样式强制转换或函数样式强制转换)

**Comment by richard-bmc** [comment]
I have the same problem in mpark\variant.hpp. There wree tons of C2131, C2975, C2440 errors.

**Comment by richard-bmc** [comment]
After update Visual Studio Community 2017 to v15.9.4, the library can be built.

**Comment by oridong** [comment]
OK，I will try it.   Thank you .      I'm very pleasure that you remind me .Nice to meet you ,I'm Chinese.


发自网易邮箱大师
On 12/27/2018 18:18，richard-bmc<notifications@github.com> wrote：

After update Visual Studio Community 2017 to v15.9.4, the library can be built.
