### ISSUE TITLE
Build Failed with Ubuntu 14.04

### ISSUE THREAD

**Issue by MohammadKassemZein** [stevenlovegrove/Pangolin#493]
When Trying to build on Ubuntu 14.04 , this error appears: 
error: expected primary-expression before ‘decltype’
/home/zein/Pangolin/include/pangolin/utils/format_string.h:46:29: error: expected ‘;’ at end of member declaration
/home/zein/Pangolin/include/pangolin/utils/format_string.h:46:53: error: invalid use of ‘::’
make[2]: *** [src/CMakeFiles/pangolin.dir/utils/uri.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2

Any Suggestions?

**Comment by Wenju-Huang** [comment]
I resolve it by updating the cmake to 3.2
