### ISSUE TITLE
compilation with ffmpeg 5.0

### ISSUE THREAD

**Issue by NikolausDemmel** [stevenlovegrove/Pangolin#737]
Looks like compilation is broken with the recently released ffmpeg 5.0 (see below). Since homebrew on macOS is rolling release, Pangolin doesn't compile on macOS out-of-the-box any more.

If you use cmake >= 3.12 (which on macOS should generally be the case) you can work around the issue by pointing cmake to ffmpeg v4 explicitly:

```
# make sure ffmpeg version 4 is installed
brew install ffmpeg@4

# explicitly point cmake to the right version of ffmpeg
cmake .. -DFFMPEG_ROOT=`brew --prefix`/opt/ffmpeg@4/ -DCMAKE_POLICY_DEFAULT_CMP0074=NEW
```

But it would be nice if Pangolin would work with ffmpeg 5.0.

This is the compilation error with current `master` on macOS Catalina with AppleClang 12, when it builds against the default ffmpeg. Looks like some API with codecs changed (or deprecated API was removed). See this [blog post](http://www.jbkempf.com/blog/post/2022/FFmpeg-5.0) about the release (or [google cached version](http://webcache.googleusercontent.com/search?q=cache:DdST4P4hE38J:www.jbkempf.com/blog/post/2022/FFmpeg-5.0+&cd=1&hl=en&ct=clnk&gl=de), since the blog post appears to be down).
```
cmake ..
[...]
make
[...]
[ 36%] Building CXX object CMakeFiles/pango_video.dir/components/pango_video/src/drivers/ffmpeg.cpp.o
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:37:
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg.h:32:
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:97:5: error: use of undeclared identifier 'AV_PIX_FMT_VAAPI_MOCO'; did you mean 'AV_PIX_FMT_VAAPI'?
    TEST_PIX_FMT_RETURN(VAAPI_MOCO);
    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:37:39: note: expanded from macro 'TEST_PIX_FMT_RETURN'
#define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
                                      ^
<scratch space>:116:1: note: expanded from here
AV_PIX_FMT_VAAPI_MOCO
^
/usr/local/include/libavutil/pixfmt.h:119:5: note: 'AV_PIX_FMT_VAAPI' declared here
    AV_PIX_FMT_VAAPI,
    ^
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:37:
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg.h:32:
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:98:5: error: use of undeclared identifier 'AV_PIX_FMT_VAAPI_IDCT'; did you mean 'AV_PIX_FMT_VAAPI'?
    TEST_PIX_FMT_RETURN(VAAPI_IDCT);
    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:37:39: note: expanded from macro 'TEST_PIX_FMT_RETURN'
#define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
                                      ^
<scratch space>:118:1: note: expanded from here
AV_PIX_FMT_VAAPI_IDCT
^
/usr/local/include/libavutil/pixfmt.h:119:5: note: 'AV_PIX_FMT_VAAPI' declared here
    AV_PIX_FMT_VAAPI,
    ^
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:37:
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg.h:32:
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:99:5: error: use of undeclared identifier 'AV_PIX_FMT_VAAPI_VLD'; did you mean 'AV_PIX_FMT_VAAPI'?
    TEST_PIX_FMT_RETURN(VAAPI_VLD);
    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:37:39: note: expanded from macro 'TEST_PIX_FMT_RETURN'
#define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
                                      ^
<scratch space>:120:1: note: expanded from here
AV_PIX_FMT_VAAPI_VLD
^
/usr/local/include/libavutil/pixfmt.h:119:5: note: 'AV_PIX_FMT_VAAPI' declared here
    AV_PIX_FMT_VAAPI,
    ^
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:37:
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg.h:32:
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:98:5: error: duplicate case value 'AV_PIX_FMT_VAAPI'
    TEST_PIX_FMT_RETURN(VAAPI_IDCT);
    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:37:39: note: expanded from macro 'TEST_PIX_FMT_RETURN'
#define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
                                      ^
<scratch space>:118:1: note: expanded from here
AV_PIX_FMT_VAAPI_IDCT
^
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:97:5: note: previous case defined here
    TEST_PIX_FMT_RETURN(VAAPI_MOCO);
    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:37:39: note: expanded from macro 'TEST_PIX_FMT_RETURN'
#define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
                                      ^
<scratch space>:116:1: note: expanded from here
AV_PIX_FMT_VAAPI_MOCO
^
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:37:
In file included from /Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg.h:32:
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:99:5: error: duplicate case value 'AV_PIX_FMT_VAAPI'
    TEST_PIX_FMT_RETURN(VAAPI_VLD);
    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:37:39: note: expanded from macro 'TEST_PIX_FMT_RETURN'
#define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
                                      ^
<scratch space>:120:1: note: expanded from here
AV_PIX_FMT_VAAPI_VLD
^
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:98:5: note: previous case defined here
    TEST_PIX_FMT_RETURN(VAAPI_IDCT);
    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/include/pangolin/video/drivers/ffmpeg_common.h:37:39: note: expanded from macro 'TEST_PIX_FMT_RETURN'
#define TEST_PIX_FMT_RETURN(fmt) case AV_PIX_FMT_##fmt: return #fmt;
                                      ^
<scratch space>:118:1: note: expanded from here
AV_PIX_FMT_VAAPI_IDCT
^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:62:5: error: use of undeclared identifier 'av_register_all'
    av_register_all();
    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:69:15: error: assigning to 'AVInputFormat *' from incompatible type 'const AVInputFormat *'
        fmt = av_find_input_format(codec_hint.c_str());
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:120:36: error: no member named 'codec' in 'AVStream'
        if(pFormatCtx->streams[i]->codec->codec_type==AVMEDIA_TYPE_VIDEO)
           ~~~~~~~~~~~~~~~~~~~~~~  ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:123:42: error: no member named 'codec' in 'AVStream'
        }else if(pFormatCtx->streams[i]->codec->codec_type==AVMEDIA_TYPE_AUDIO)
                 ~~~~~~~~~~~~~~~~~~~~~~  ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:139:54: error: no member named 'codec' in 'AVStream'
    pVidCodecCtx = pFormatCtx->streams[videoStream]->codec;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:142:15: error: assigning to 'AVCodec *' from incompatible type 'const AVCodec *'
    pVidCodec=avcodec_find_decoder(pVidCodecCtx->codec_id);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:180:17: error: use of undeclared identifier 'avpicture_get_size'
    numBytesOut=avpicture_get_size(fmtout, w, h);
                ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:185:21: error: use of undeclared identifier 'AVPicture'
    avpicture_fill((AVPicture *)pFrameOut, buffer, fmtout, w, h);
                    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:185:32: error: expected expression
    avpicture_fill((AVPicture *)pFrameOut, buffer, fmtout, w, h);
                               ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:254:13: error: use of undeclared identifier 'avcodec_decode_video2'; did you mean 'avcodec_decode_subtitle2'?
            avcodec_decode_video2(pVidCodecCtx, pFrame, &gotFrame, &packet);
            ^~~~~~~~~~~~~~~~~~~~~
            avcodec_decode_subtitle2
/usr/local/include/libavcodec/avcodec.h:2531:5: note: 'avcodec_decode_subtitle2' declared here
int avcodec_decode_subtitle2(AVCodecContext *avctx, AVSubtitle *sub,
    ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:254:49: error: cannot initialize a parameter of type 'AVSubtitle *' with an lvalue of type 'AVFrame *'
            avcodec_decode_video2(pVidCodecCtx, pFrame, &gotFrame, &packet);
                                                ^~~~~~
/usr/local/include/libavcodec/avcodec.h:2531:65: note: passing argument to parameter 'sub' here
int avcodec_decode_subtitle2(AVCodecContext *avctx, AVSubtitle *sub,
                                                                ^
/Users/demmeln/work/slam/Pangolin/components/pango_video/src/drivers/ffmpeg.cpp:264:9: error: use of undeclared identifier 'av_free_packet'; did you mean 'av_init_packet'?
        av_free_packet(&packet);
        ^~~~~~~~~~~~~~
        av_init_packet
/usr/local/include/libavcodec/packet.h:506:6: note: 'av_init_packet' declared here
void av_init_packet(AVPacket *pkt);
     ^
17 errors generated.
make[2]: *** [CMakeFiles/pango_video.dir/components/pango_video/src/drivers/ffmpeg.cpp.o] Error 1
make[1]: *** [CMakeFiles/pango_video.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by NikolausDemmel** [comment]
PS: just noticed that this also shows in CI on current master: https://github.com/stevenlovegrove/Pangolin/runs/5242984707?check_suite_focus=true

**Comment by lichengqi0805** [comment]
Same issue here

**Comment by stevenlovegrove** [comment]
There is a WIP branch [here](https://github.com/stevenlovegrove/Pangolin/tree/ffmpeg5) which compiles and works against ffmpeg5 for video input but is missing VideoOutput for now. If you're desperate you can try it. Remember that you can always disable ffmpeg in cmake if you don't need it on your platform.

**Comment by stevenlovegrove** [comment]
The build is now fixed and ffmpeg 5 is supported along with recent versions prior to 5. As a bonus, I finally added proper seek support for the ffmpeg driver, though the time base for recorded video with the VideoOutputDriver is not quite right.

https://github.com/stevenlovegrove/Pangolin/commit/b5053df632c93a38f47c495885b528bb1adbb344

**Comment by NikolausDemmel** [comment]
Awesome, thanks for the fix!
